---
title: "Rockfish Historical Harvest Estimates"
author: "Adam Reimer"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(ggplot2)
library(tidyverse)

```

## Data
Harvest data was available for 22 commercial fishing management areas in Southcentral and SOutheast Alaska. Areas with negligible rockfish harvest were pooled with adjacent areas for analysis. Specifically the Aleutian and Bering areas were pooled into an area labeled BSAI; the IBS and EKYT were pooled into an area labeled EKYKT; the Southeast, Southwest, SAKPEN and Chignik areas were pooled into an area labeled SOKO2PEN and the Westside and Mainland areas were pooled into an area labeled WKMA.

### Stateside Harvest Survey (SWHS)
Statewide harvest survey estimates of rockfish catch and harvest are available for 24 years (1996-2019) for all users and for 9 years (2011-2019) for guided anglers. SWHS estimates are believed to be biased as the are often smaller than reported harvest from guide logbook programs.

### Creel Surveys


### Guide Logbooks
Sport fishing guides were required to report their harvest of rockfish catch and harvest for 22 years (1998-2019). Reported harvest is also available by assemblage (pelagic vrs. non-pelagic). Harvest of yelloweye rockfish were reported separately beginning in 2006.

### Composition data
Harvest sampling data exists from Gulf of Alaska areas since 1993 and from Southeast Alaska areas since 2006.

## Analysis
The true harvest of rockfish $H_{ay}$ for area $a$ during year $y$ is assumed to follow a temporal trend defined by a penalized spline:

\begin{equation}
H_{ay}~\sim~\textrm{Normal}(f(a,y)), 0.25)
\end{equation} 

where $f(a,y)$ in a p-spline basis with 8 components with a second degree penalty and a variance of 0.25 was assumed to allow substantial viability around the spline. SWHS estimates of annual rockfish harvest $SWHS_{ay}$ were assumed to index true harvest:

\begin{equation}
\widehat{SWHS}_{ay}~\sim~\textrm{LogNormal}\left(\textrm{log}\left(\frac{H_{ay}}{b_{ay}}\right), \sigma_{(SWHS)ay}^2\right)
\end{equation}

where bias in the SWHS estimates $b_{ay}$ is modeled hierarchically across years as:

\begin{equation}
b_{ay}~\sim~\textrm{Normal}(\mu_{(b)a}, \sigma_{(b)a})
\end{equation}

with non-informative priors on both parameters. Reported guide logbook harvest is related to true harvest as:

\begin{equation}
\widehat{LB}_{ay}~\sim~\textrm{Poisson}\left(\textrm{log}(H_{ay}P_{(G)ay})\right)
\end{equation}

where the proportion of rockfish harvested by guided anglers $P_{(G)ay}$ is modeled hierarchically across years as:

\begin{equation}
P_{(G)ay}~\sim~\textrm{beta}(\lambda1_a, \lambda2_a)
\end{equation}

with non-informative priors on both parameters. SWHS estiamtes of guided angler harvest are related to toal harvest by:

\begin{equation}
\widehat{SWHS}_{(G)ay}~\sim~\textrm{LogNormal}\left(\textrm{log}\left(\frac{H_{ay}P_{(G)ay}}{b_{ay}}\right), \sigma_{(SWHS_{(G)})ay}^2\right)
\end{equation}
