---
title: "Rockfish Removals in Alaska Sport Fisheries 1977 - 2023"
author: "Philip Joy"
output:
  word_document:
    reference_docx: "rep_temp_wtc.docx"
    toc: true
    toc_depth: 2
fontsize: 12pt
#date: "2025-05-23"

#knit: (function(input_file, encoding) {
#        rmarkdown::render(input_file, 
#                          output_file = paste0("RFsportmort_update_", "theModel_prelim_",Sys.Date(),".html"))
#      })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

getwd()
file.exists("../scripts/bayes_data_param_load.R")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(ggplot2)
library(tidyverse)
library(wesanderson)
library(ggpubr)
library(knitr)
library(kableExtra)
library(here)
library(htmltools) 
library(coda)
library(jagsUI)
library(stringr)
library(readxl)
library(openxlsx2)
library(scales)
library(xlsx)
library(writexl)

source("../scripts/mkdwn_functions.R", echo = FALSE)
#source("./scripts/bayes_data_param_load", echo = FALSE)
start_yr <- 1977
end_yr <- 2023
REP_YR <- 2023 #for Howard estimates
list2env(readinData(start_yr = start_yr,
                  end_yr = end_yr),
         .GlobalEnv)

#...............................................................................
##!!!FLAG: CHANGE THIS IN THE KNIT FUNCTION ABOVE TO PROPERLY LABEL HTML FILE!!!!!!
#...............................................................................
# Notes: on p plot, make symbol size = sample size, 
# Figure out how to show pH "data" for private? swhs bias and how species comps add up to match total releases. pH_pri_comp = pH_pri_all (bias corrected) ~ pH_gui_comp w offset parameter. Calculate pH_pri_all and show range based on species apportionment that illustrates model keeping sum of species = all release estimates
# comp_H - total_release * unkown comp proportion
#-------------------------------------------------------------------------------8
#mod<-"LB_hyb_5pH_infPr"
#mod<-"LB_fit_5pH"
mod<-"LB_fit_3pH"
#mod<-"LB_hyb_3pH"
res <- "rf_harvest_est_kha_rm_wt_thru2023_480000_7kn_2025-05-23"
#res <- "HR_fitLBR_2bias_hierPcomp_3pH_infPr_thru2023_2e+06_7kn_2025-01-25"
res <- "rf_harvest_est_nm_wt_thru2023_1500000_nm_wts_sd7_2025-06-02"

postH <- readRDS(paste0("..\\output\\bayes_posts\\",res,".rds"))

rhat <- get_Rhat(postH, cutoff = 1.11)

summary_table <- postH$summary %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "Parameter") %>%
  select(Parameter, mean, sd, `2.5%`, `50%`, `97.5%`) %>%
  rename(
    Lower_CI = `2.5%`,
    Median = `50%`,
    Upper_CI = `97.5%`
  ) %>% 
  filter(str_detect(Parameter, "^tau_comp\\[") |
         str_detect(Parameter, "^tau_pH\\[") |
          str_detect(Parameter, "^mu_beta0_pelagic\\[")|
           str_detect(Parameter, "^tau_beta0_pelagic\\[")|
           str_detect(Parameter, "^mu_beta0_yellow\\[")|
           str_detect(Parameter, "^tau_beta0_yellow\\[")|
           str_detect(Parameter, "^mu_beta0_black\\[")|
           str_detect(Parameter, "^tau_beta0_black\\[")|
           str_detect(Parameter, "^mu_beta0_yellow_x\\[")|
           str_detect(Parameter, "^tau_beta0_yellow_x\\[")|
           str_detect(Parameter, "^mu_bc_H\\[")|
           str_detect(Parameter, "^tau_bc_H\\[")|
           str_detect(Parameter, "^mu_bc_R\\[")|
           str_detect(Parameter, "^tau_bc_R\\[")|
           str_detect(Parameter, "^bc_R_offset\\[")|
           str_detect(Parameter, "^beta0_pH\\[")|
           str_detect(Parameter, "^beta1_pH\\[")|
           str_detect(Parameter, "^beta2_pH\\[")|
           str_detect(Parameter, "^beta3_pH\\[")|
           str_detect(Parameter, "^beta0_pelagic\\[")|
           str_detect(Parameter, "^beta1_pelagic\\[")|
           str_detect(Parameter, "^beta2_pelagic\\[")|
           str_detect(Parameter, "^beta3_pelagic\\[")|
           str_detect(Parameter, "^beta0_yellow\\[")|
           str_detect(Parameter, "^beta1_yellow\\[")|
           str_detect(Parameter, "^beta2_yellow\\[")|
           str_detect(Parameter, "^beta3_yellow\\[")|
           str_detect(Parameter, "^beta0_black\\[")|
           str_detect(Parameter, "^beta2_black\\[")|
           str_detect(Parameter, "^beta3_black\\[")|
           str_detect(Parameter, "^beta4_black\\[")|
           str_detect(Parameter, "^beta0_dsr\\[")|
           str_detect(Parameter, "^beta1_dsr\\[")|
           str_detect(Parameter, "^beta2_dsr\\[")|
           str_detect(Parameter, "^beta3_dsr\\[")|
           str_detect(Parameter, "^beta4_dsr\\[")|
           str_detect(Parameter, "^beta0_slope\\[")|
           str_detect(Parameter, "^beta1_slope\\[")|
           str_detect(Parameter, "^beta2_slope\\[")|
           str_detect(Parameter, "^beta3_slope\\[")|
           str_detect(Parameter, "^beta4_slope\\[")|
           str_detect(Parameter, "^sigma_H\\[")|
           str_detect(Parameter, "^beta_H\\[")|
           str_detect(Parameter, "^beta0_H\\[")|
           str_detect(Parameter, "^lambda_H\\[")|
           str_detect(Parameter, "^mu_lambda_H\\[")|
           str_detect(Parameter, "^sigma_lambda_H\\["))

X <- 0

southeast <- c("CSEO","EWYKT","NSEI","NSEO","SSEI","SSEO")
central <- c("CI","NG","PWSI","PWSO")
kodiak <- c("BSAI","SOKO2SAP","WKMA","afognak","eastside","northeast")
```

# Abstract

Fishery stock assessments require defensible estimates of total extractions (commercial, sport, subsistence, personal use, and bycatch) throughout the history of exploitation and at appropriate spatial scales for management. This study provides updated estimates of total sport harvest and releases for black and yelloweye rockfishes as well as demersal shelf, slope and non-black pelagic rockfish in southeast, in geographic units consistent with commercial fishery management units (CFMUs), and incorporates release mortalities and fish weights to estimate total fishing mortality in pounds. The new methods build on the foundational work of Howard et al. (2020) that developed the spatial relationsihip between sport and commercial fishery management units and provided estimates between 1999 and today. The Bayesian methods used here allow for estimation back through 1977, corrects some assumptions in the Howard methodology, and provides a unified and reproducible approach to estimating sport fishing mortalities. Sport harvest and release information is available from Alaska Department of Fish and Game saltwater guide logbooks and the Alaska Sport Fishing Survey (commonly known as the statewide harvest survey or SWHS). Guide logbooks have provided a census of guided sport harvest and release by statistical reporting areas and by pelagic and nonpelagic rockfish assemblages since 1998/1999, and a census of yelloweye rockfish harvest and release since 2006. The SWHS has provided estimates of harvest and catch by guided and unguided anglers. Port sampling data provides estimates of species composition in the harvest as well as length and weight data. The Bayesian model calculates harvests very similar to the methods used in Howard et al. (2020) but relies on a process driven approach rather than relying on assumptions about the SWHS data. Bias in the SWHS harvest and release numbers are corrected in the model and the Bayesian model does not make the Howard et al. (2020) assumption that the species composition of the harvest is equal to that of the released fish. The Bayesian model also uses a hierarchical approach such that information is more appropriately shared across areas within regions and more appropriately propogates error. Assumptions about key parameters and estimates before data collection began are made using logistic curves to estimate trends. Harvest estimates from the Bayesian model are very similar to the Howard et al. (2020) estimates but release estimates differ considerably as a result of bias correction and more informed estimates of release probability by species and species assemblage as evident in the logbook data. Sport black and yelloweye rockfishes harvests and releases provided by this methodology are recommended for use in stock assessments of these species statewide, and the methodology could be useful for other marine finfish species where stock assessment models are needed.

Keywords: sport fish, harvest, release, fishing mortality, black rockfish, yelloweye rockfish, demersal shelf rockfish, slope rockfish, pelagic rockfish, Gulf of Alaska, *Sebastes*, *Sebastes melanops*, *Sebastes ruberrimus*, rockfish

# Introduction

Rockfish (*Sebastes spp*) harvests in Alaskan waters have become an increasing concern as restrictions on halibut and salmon has led to increased pressure on rockfish stocks. In response to this pressure, the Alaska Department of Fish and Game (ADF&G) initiated an interdivisional, inter-regional strategic plan to develop long-term management and stock assessment strategies for black rockfish (*S. melanops*) and yelloweye rockfish (*S. ruberrimus*) across the Gulf of Alaska (GOA) (Howard et al. 2019a). The first step in assessing any fish stock is to have an accurate and complete history of fishery removals from the stock. While commercial fisheries relies on a fish ticketing system that censuses the harvest, Alaska sport fisheries rely on a number of programs, phased in over time, to account for rockfish removals in the sport fishery. 

Sport fishery harvests are measured through a variety of programs, primarily the Alaska Sport Fishing Survey (commonly known as the statewide harvest survey or SWHS), the saltwater guide logbook program, and sampling programs at primary ports. The SWHS was initiated in 1977 as an annual mail-out survey (Romberg et al. 2018). Response to this survey is voluntary and the survey design provides for estimates of statewide harvest and catch (since 1990) in numbers of fish for rockfish (all species combined) and effort in saltwater angler days (for all marine species combined) by unguided and guided anglers (since 2011) and by predefined geographical strata. SWHS strata are not geographically consistent with either sport rockfish fishery management areas or commercial fisheries management units (CFMUs) but have been assigned as such based on methods developed by Howard et al. (2020). 

The guided logbook program was established in 1998 to acquire information on guided industry harvests and releases by species and effort (Powers 2015). In addition to other species such as salmon and halibut, this mandatory program provides a census of harvest and release in numbers of pelagic and nonpelagic rockfish species assemblages and, since 2006, yelloweye rockfishes. The logbook program also provides information on the statistical area where fishing occurred. 

Sport harvest port sampling programs provide information on biological characteristics of the harvest, including species composition (Jaenicke et al. 2019; Failor 2016). Port sampling programs vary regionally in their design, history, and information collected. The estimation of release mortalities in commercial and sport fisheries presents additional challenges for understanding total fishing mortality. The ability to estimate total removals by both sport and commercial fisheries will enable assessment of harvest rates and be useful for future stock assessments.

Yelloweye and black rockfish removal estimation methods were originally developed by Howard et al. (2020; hereafter refered to as the Howard methods), which included spatial partitioning of the data, identifying bias in the SWHS survey estimates relative to the logbook census of guided anglers, and estimating unguided harvests and releases by expanding logbook catch and release data using the proportions of guided:unguided harvests and releases from SWHS data. This approach was both novel and critical in providing harvest and release estimates for managers to understand the magnitude of the catch and to allow accurate assessments of stocks. 

While the Howard methods provide the baseline for understanding and reconstructing rockfish harvests in Alaska, the methods had several shortcomings and recommendations for reevaluation as more data and improved methodologies become available. The Howard methods were limited to the period since the logbook program was brought online in 1998 and thus only provides estimates since that time even though rockfish have been harvested by sport anglers since the 1960s or earlier. The methods also rely on a "decision tree" approach to deal with missing data and inadequate sample sizes by using long term averages or proxy values from neighboring management areas. Furthermore, while the Howard methods address bias in the SWHS data, it is not implicitly estimated or corrected and, whats more, ignores potential differences in the bias of harvest and release data. In particular, the estimation of unguided harvests and releases relies on an expansion of logbook data based on the guided:unguided ratio in the SWHS data, regardless of species or species complex. 

The methods presented here build on the foundational Howard methods by applying a Bayesian approach to expand the harvest and release time series back to 1977 when the SWHS was first implemented, estimating and correcting bias in the SWHS harvest and release data, allowing release probabilities to vary by species / species assemblage, and replace the decision tree approach with a hierachichal model that more accurately and efficiently shares information between areas within regions (Table HOWARD_VS_BAYES). To make estimates prior to the Howard estimates the Bayesian model estimates trends in species proportions and harvest/release probability to project backwards in time while explicitly estimating bias in the SWHS harvest and release data. Furthermore, the model's hierarchichal structure allows information on these trends, as well as overall harvest trends, to be shared among management areas within the three main regions (Southeast, Southcentral and Kodiak) without having to use proxy values and more effectively propagates error throughout the process. The model incorporates fish weight and release mortality probabilities (CITATION) so that previously unpublished total removal estimates in biomass are also produced in one place. These methods provide a more streamlined and reproducible approach to deriving rockfish removal estimates.  

# Objective

1) Estimate annual sport harvests,releases and total removals in biomass of rockfishes in Gulf of Alaska CFMUs from 1977–2023. Southcentral and Kodiak CFMUs include estimates for black and yelloweye rockfish while Southeast CFMU's include estimates of black, yelloweye, non-black pelagic (dark *S. ciliates*, dusky *S. variabilis*, widow *entomelas*, yellowtail *S. flavidus*, and blue *S. mystinus* rockfish), non-yelloweye demersal shelf (canary *S. pinniger*, quillback *S. maliger*, china *S. nebulosus*, copper *S. caurinus*, rosethorn *S. helvomaculatus* and tiger *S. nigrocinctus* rockfish), and slope rockfish (redbanded *S. babcocki* , rougheye *S. aleutianus*, silvergray *S. brevispinis*, shortraker *S. borealis*, and vermillion *S. miniatus* rockfish). 

# Study Area

Reconstructions were developed for CFMUs across the Gulf of Alaska, from Kodiak Island east to Southeast Alaska. CFMUs were divided into 3 overall regions such that the Southcentral region contained Cook Inlet (CI), the North Gulf Coast (NG) (Figure CING_CFMUs) and Prince William Sound Inside (PWSI) and Outside (PWSO) CFMU's (Figure PWS_CFMUs) and Southeast region was comprised of the Central Southeast Outside (CSEO), North Southeast Outside (NSEO), South Southeast Outside (SSEO), North Southeast Inside (NSEI), South Southeast Inside (SSEI) and a sixth area that pooled the Icy Bay subdistrict (IBS) and East Yakutat section (EYKT) to comprise the East–West Yakutat management area (EWYKT) (Figure SE_CFMUs). 

Several of the westward and Kodiak subdistricts have little data and necessitated pooling for this analysis (Figure KOD_CFMUs). In addition to the Afognak, Eastside and Northeast CFMUs which contained adequate data, the Westside and Mainland districts were pooled to form the Western Kodiak management area (WKMA) while the Southeast, Southwest, Chignik and South Alaska Peninsula (SAKPEN) districts were pooled into a CFMU called SOKO2PEN. Lastly the Aleatian and Bering Sea CFMUs were pooled into the BSAI CFMU and included in the Kodiak region.

# Methods

## Data

Statewide harvest survey estimates of rockfish catch and harvest are available for 28 years (1996-2023) for all users and for 13 years (2011-2023) for guided anglers (Figure DATA_SOURCES). Additionally, there are overall harvest estimates from 1977- 1995 and release estimates from 1990-1995 that required some partitioning to ascribe to current management units using the Howard methods. Harvest and release estimates in unknown areas were apportioned based on harvest proportions in 1996. Variance estimates are not available for pre-1996 data and as such, the maximum observed coefficient of variation (cv) in each commercial fisheries management unit was applied to the pre-1996 values. 

SWHS Rockfish release estimates are inferred from the difference between catch and harvest estimates and variances calculated accordingly. SWHS release estimates were assumed to equal the total catch minus the harvest and the standard deviation of the releases was derived from the standard deviation of the harvest and catch estimates such that 

$\sigma_{SWHS_R} ~=~ \sqrt{\sigma_{SWHS_H}^2 + \sigma_{SWHS_C}^2}$

Sport fishing guides have been required to report their harvest of rockfish for 26 years (1998-2023) and releases for 25 years (1999-2023). Reported harvest and releases is also available by assemblage (pelagic vs. non-pelagic) for the entirety of the program while harvest and release of yelloweye and “other” (non-pelagic, non-yelloweye) rockfish were reported separately beginning in 2006. Logbook data is treated as a census of the true catch and release of rockfish in these categories. 

SWHS estimates of harvests and releases are assumed to be biased based on the disagreement between SWHS estimates of guided trips and matching logbook totals of guided harvests and releases (Figure DATA BIAS; Howard et al. 2020). Additionally, the bias in harvests and releases varies considerably in both direction and magnitude (Figure DATA BIAS). The model treats the logbook data as a census with minimal uncertainty and thus SWHS bias estimation is a product of the difference between the survey and the logbook data. This bias is thus corrected in the model estimation.

Harvest sampling data exists from Gulf of Alaska areas since 1996 and from Southeast Alaska areas since 2006 (CITATIONS?). Port sampling data is comprised of the number of total rockfish, pelagic and non-pelagic rockfish, black rockfish and yelloweye rockfish. In Southeast Alaska, the number of demersal shelf rockfish (DSR, of which yelloweye are one species) and slope rockfish are also recorded.

*WEIGHT DATA FROM WHERE?* chris and Clay

*RELEASE MORTALITY DATA FROM WHERE?* Chris, Clay. Insert depth methods here.

Annual release mortality estimates in Southcentral and Kodiak were then calculated by averaging the the mortality-at-depth estimates weighted by the estimated proportion released at depth.

*KODIAK HYDROACOUSTIC HERE* Port sampling for outlying areas in Kodiak are unavailable to inform species compositions and thus are largely reliant on the hierarchichal structure of the model to derive estimates from the sampled areas. However, ADF&G commercial fisheries division has a robust hydroacoustic survey around the island to estimate black rockfish abundance and as part of that survey estimates species compositions of the pelagic rockfish communities in this area (CITATION). This was used as supplemental data to further inform the species composition in the Kodiak CFMUs.

## Process equations

### Harvests

The true harvest $H_{ay}$ of rockfish for area $a$ during year $y$ is assumed to follow a temporal trend defined by a penalized spline:

$\textrm{log}(H_{ay})~\sim~\textrm{Normal}(f(a,y), {\sigma_{Ha}})$

where $f(a,y)$ in a p-spline basis with 7 components (knots) and a second degree penalty (Eiler and Marx 1996; Ruppert et al. 2003; Lang and Brezger 2004; Appendix A) and $\sigma_{Ha}$ is the variance (Table PRIORS1). The spline was modeled hierarchically within regions (Table PRIORS1, Appendix A).  

Harvests were apportioned by user groups such that charter and private harvest $H_{ayu}$ (where *u* = 1 for charter anglers and *u* = 2 for private anglers) is a fraction of total annual harvest in each area:

$H_{ay1}~=~H_{ay}P_{(user)ay1}$

$H_{ay2}~=~H_{ay}(1-P_{(user)ay1})$

where $P_{(user)ay1}$ is the fraction of the annual harvest in each area taken by charter anglers.  $P_{(user)ay1}$ was modeled hierarchically across years as:

$P_{(user)ay1}~\sim~\textrm{beta}(\lambda1_a, \lambda2_a)$

with non-informative priors on both parameters (Table PRIORS1).

### Species Apportionment

The total harvest of rockfish is apportioned to species and species complexes beginning with a partition into pelagic and non-pelagic categories such that

$H_{(pelagic)ayu}~=~H_{ayu}*P_{(pelagic)ayu}$

and

$H_{(non-pelagic)ayu}~=~H_{ayu} - H_{(pelagic)ayu}$

where $P_{(pelagic)ayu}$ is the fraction of the annual harvest for each area and user group that was pelagic rockfish. Black rockfish are a subset of the pelagic assemblage and as such annual black rockfish harvest $H_{(black)ayu}$ for each area and user group is:

$H_{(black)ayu}~=~H_{ayu}*P_{(pelagic)ayu}*P_{(black|pelagic)ayu}$

where $P_{(black|pelagic)ayu}$ is the fraction of the annual harvest of pelagic rockfish for each area and user group that was black rockfish.

In southcentral and Kodiak regions yelloweye rockfish comprise a component of the non-pelagic assemblage such that the harvest of yelloweye

$H_{(yelloweye)ayu}~=~H_{ayu}(1-P_{(pelagic)ayu})P_{(yelloweye|non-pelagic)ayu}$

where $P_{(yellow|non-pelagic)ayu}$ is the fraction of the annual harvest of non-pelagic rockfish for each area and user group that was yelloweye rockfish.

The southeast region also tracks two other non-pelagic rockfish assemblages, demersal shelf rockfish (DSR, which includes yelloweye) and slope rockfish. For the southeast region the harvest of those two assemblages is thus

$H_{(DSR)ayu}~=~H_{ayu}(1-P_{(pelagic)ayu})P_{(DSR|non-pelagic)ayu}$

$H_{(slope)ayu}~=~H_{ayu}(1-P_{(pelagic)ayu})P_{(slope|non-pelagic)ayu}$

where $P_{(DSR|non-pelagic)ayu}$ and $P_{(slope|non-pelagic)ayu}$ are the fractions of the annual harvest of non-pelagic rockfish for each area and user group that were DSR and slope rockfish, respectively. Yelloweye rockfish belong to the DSR complex so southeast areas yelloweye harvests are a fraction of the DSR harvests such that

$H_{(yelloweye)ayu}~=~H_{(DSR)ayu}*P_{(yelloweye|DSR)ayu}$

Species composition data is not available for the entire time series and as such it was necessary to assume some trend in the data to project backwards in time. To do so, we fit a logistic curve to the species composition data that would account for shifts in the species composition during the observed time period but would not extrapolate beyond the limits of the observed data when hindcasting. Thus, the composition parameters $P_{(comp)ayu}$, were modeled using a logistic curve such that:

$\textrm{logit}(P_{(comp)ayu})~=~\beta0_{(comp)ayu} + \frac{\beta1_{(comp)ayu}}{(1 + exp(\beta2_{(comp)ayu}*(y - \beta3_{(comp)ayu})))} + \beta4_{(comp)ayu}*I(u=private)+re_{(comp)ayu}$

where the $\beta$ parameters define the intercept, scaling factor, slope, inflection point and private angler effect, respectively, $y$ is the year index, $I(u=private)$ is an index variable which is 1 when the user groups is private and 0 otherwise and $re_{(comp)ayu}$ is a random effect with a non-informative prior that estimates deviation from the fit line. $\beta$ parameters were modeled hierarchically by region. When $\beta$ parameters were inestimable as a result of no discernible change in composition over the observed time period $\beta1$ (scaling factor) and $\beta2$ (slope) were fixed to 0 so that the long term mean value was used for hindcasting (Table pH_PRIORS). 

### Releases

The procedure for estimating releases differs from the Howard methods in that it relies on a process driven approach in contrast to the estimation methods employed in Howard et al. (2020; Figure REL_SCHEMATICS). Rather than making the assumption that the guided:unguided ratio of total rockfish releases in the SWHS data is an appropriate way to derive unguided releases of each species complex from the logbook record of releases, this approach models releases based on the harvests and the probability that a landed fish is retained separately for each of the three logbook categories (pelagic, yelloweye, and "other"). Thus, the true number of released rockfish $R_{ayu}$ were based on the proportion of the total catch harvested (also referred to as retention probability), $pH_{(comp)ayu}$, by area, year, user group and species grouping. Because release data from the SWHS is for all rockfish and the release data from logbooks is only subdivided into pelagics, yelloweye and "other" (non-pelagic, non-yelloweye), we only estimated $pH_{(comp)ayu}$ for those categories. Thus, converting $H_{(comp)ayu}$ to total catches by user group, $C_{(comp)ayu}$, with $pH_{(comp)ayu}$ results in estimates of total releases such that

$R_{(comp)ayu}~=~ C_{(comp)ayu} - H_{(comp)ayu} ~=~ \frac{H_{(comp)ayu}}{pH_{(comp)ayu}} - H_{(comp)ayu}$

with total releases equal to the sum of the compositional releases. For non-yelloweye DSR and Slope rockfish assemblages in Southeast Alaska $R_{(DSR)ayu}$ and $R_{(slope)ayu}$ were estimated from $R_{(other)ayu}$ using the species composition data from the harvest, thus assuming that slope and DSR assemblages were caught and released at the same rates.

The proportion harvest parameters for $pH_{(comp)ayu}$ were modeled using a logistic curve that would allow hindcasting based on trends in the data without extrapolating beyond the range of observed values such that

$\textrm{logit}(pH_{ayuc})~=~\beta0_{(pH)ayuc} + \frac{\beta1_{(pH)ayuc}}{(1 + exp(\beta2_{(pH)ayuc}*(y - \beta3_{(pH)ayuc})))} + \beta4_{(pH)ayuc}*I(u=private)+re_{(pH)ayuc}$

where the $\beta$ parameters define the intercept, scaling factor, slope, inflection point and private angler effect, respectively, $y$ is the year index, $I(u=private)$ is an index variable which is 1 when the user groups is private and 0 otherwise and $re_{(comp)ayu}$ is a random effect with a non-informative prior that estimates deviation from the fit line. The random effect term allowed estimation during the historical period when data is available, but the curve defined by the above equation determined release estimates between 1977 and 1990. As with the compositional trends, $\beta$ parameters were modeled hierarchically by region. When $\beta$ parameters were inestimable as a result of no discernable change in harvest probability over the observed time period, $\beta1$ (scaling factor) and $\beta2$ (slope) were fixed to 0 so that the long term mean value was applied. 

It was assumed that $pH_{(black)ayu}$ was equal to $pH_{(pelagic)ayu}$ given the dominance of that species within the assemblage. For southeast Alaska, there was no way to estimate $pH_{(DSR)ayu}$ or $pH_{(slope)ayu}$ and so $P_{(DSR)ayu}$ and $P_{(slope)ayu}$ were applied to the $R_{(other)ayu}$ estimates to generate estimates of $R_{(DSR)ayu}$ and $R_{(slope)ayu}$. The assumption that DSR and slope rockfish would be released in similar proportions was deemed reasonable given that these species tend to be caught in similar habitat with similar methods and these species are regarded comparably by anglers.

Estimating the proportion of slope rockfish in the releases required adding a fifth $\beta$ term to equation LOGITSPECIESCOMP to account for yelloweye being included separately. This term offset the overall $P_{(slope)ayu}$ logit curve to differentiate $P_{(slope)ayu}$ in the harvests and releases.    

Release mortality (i.e., the number of released rockfish expected to die) was calculated assuming fixed mortality rates developed in each of the regions. Deep water release (DWR) devices were mandated for charter fleets in 2013 and rates were derived from CITATION. Southeast applies basic rates estimated in these studies while Southcentral and Kodiak rates were derived by using historical depth-of-release data to adjust the rates based on area and user group (FIGURE DWR).

The total number of mortalities by year, area, user and species/species assemblage in numbers was calculated by summing harvests and release mortality such that

$M_{(comp)ayu}~=~ H_{(comp)ayu} + m_{R-(comp)ayu} * R_{(comp)ayu}$

where $m_{R-(comp)ayu}$ is the release mortality rate by year, area, user and species (Figure XX). 

### Biomass conversions

Total removals in biomass were converted using the average weight of fish **from port sampling?**. A minimum sample size per year of **X** fish was used as the cutoff for including in the data set. Weights were modeled hierarchically to estimate weights in years when data was missing. The total biomass of removals by year, area, user and species was thus

$B_{(comp)ayu}~=~ \overline{wt}_{(comp)ayu} * M_{(comp)ayu}$

where $\overline{wt}_{(comp)ayu}$ is the mean weight by species, area, user and year. 

## Observation equations

The process model was fit to the SWHS, logbook and port sampling data using the following equations. SWHS estimates of annual rockfish **harvest** $\widehat{SWHS}_H{ay}$ were assumed to index true harvest:

$\widehat{SWHS}_H{ay}~\sim~\textrm{LogNormal}\left(\textrm{log}(H_{ay}b_{ay}), \sigma_{SWHSHay}^2\right)$

where bias in the SWHS harvest estimates $b_H{ay}$ is modeled hierarchically across years as:

$b_H{ay}~\sim~\textrm{Normal}(\mu_H{(b)a}, \sigma_H{(b)a})$

with non-informative priors on both parameters (Table PRIORS). SWHS estimates of guided angler harvest $\widehat{SWHS}_H{ay1}$ are thus related to total harvest by:

$\widehat{SWHS}_H{ay1}~\sim~\textrm{LogNormal}\left(\textrm{log}(H_{ay1}b_{ay}), \sigma_{SWHS_{ay1}}^2\right)$

Reported guide logbook harvest $\widehat{LB}_H{ay}$ are considered a census of the true harvest and is related to true harvest as:

$\widehat{LB}_H{ay}~\sim~\textrm{Poisson}(H_{ay1})$

$\widehat{LB}_H{(pelagic)ay}~\sim~\textrm{Poisson}(H_{ay1}P_{(pelagic)ay1})$

$\widehat{LB}_H{(yelloweye)ay}~\sim~\textrm{Poisson}(H_{(yelloweye)ay1})$

$\widehat{LB}_H{(nonpel,nonye)ay}~\sim~\textrm{Poisson}(H_{(nonpel,nonye)ay1})$

Note that for central and Kodiak areas $H_{(nonpel,nonye)ay1}$ is equal to the total harvest minus pelagic and yelloweye harvests. For southeast areas $H_{(nonpel,nonye)ay1}$ is equal to the sum of the DSR and slope harvests *minus* yelloweye harvests.

SWHS estimates of annual rockfish **releases** $\widehat{SWHS}_R{ay}$ were assumed to index true releases similarly to harvests and were modeled such that:

$\widehat{LB}_R{ay}~\sim~\textrm{Poisson}(R_{ay1})$

$\widehat{LB}_R{(pelagic)ay}~\sim~\textrm{Poisson}(R_{ay1}P_{(pelagic)ay1})$

$\widehat{LB}_R{(yelloweye)ay}~\sim~\textrm{Poisson}(R_{(yelloweye)ay1})$

$\widehat{LB}_R{(nonpel,nonye)ay}~\sim~\textrm{Poisson}(R_{(nonpel,nonye)ay1})$

SWHS estimates of guided angler release $\widehat{SWHS}_R{ay1}$ is modeled the same as harvests, but assumed a different bias such that

$b_R{ay}~\sim~\textrm{Normal}(\mu_R{(b)a}, \sigma_R{(b)a})$

where bias in the SWHS release estimates $b_R{ay}$ is modeled hierarchically across years as:

$b_R{ay}~\sim~\textrm{Normal}(\mu_R{(b)a}, \sigma_R{(b)a})$

with non-informative priors on both parameters.

The number of pelagic rockfish sampled in harvest sampling programs $x_{(pelagic)ayu}$ follow a binomial distribution:

$x_{(pelagic)ayu}~\sim~\textrm{Binomial}(P_{(pelagic)ayu}, N_{ayu})$

where $N_{ayu}$ is the total number of rockfish sampled in area $a$ during year $y$ form user group $u$. The number of black rockfish sampled in harvest sampling programs was thus a proportion of the pelagic harvests

$x_{(black)ayu}~\sim~\textrm{Binomial}(P_{(black)ayu}, N_{ayu}^{pel})$

where $N_{ayu}^{pel}$ is the total number of pelagic rockfish. Yelloweye rockfish in Southcentral and Kodiak were modeled similarly as a proportion of the total number of non-pelagics such that 

$x_{(yellow_{R2})ayu}~\sim~\textrm{Binomial}(P_{(yellow_{R2})ayu}, N_{ayu}^{nonpel})$

Southeast areas have several other non-pelagic groupings such that DSR and slope rockfish are a proportion of non-pelagics

$x_{(DSR)ayu}~\sim~\textrm{Binomial}(P_{(DSR)ayu}, N_{ayu}^{nonpel})$

and

$x_{(slope)ayu}~\sim~\textrm{Binomial}(P_{(slope)ayu}, N_{ayu}^{nonpel})$

with yelloweye in southeast a proportion of the DSR harvest

$x_{(yellow_{R1})ayu}~\sim~\textrm{Binomial}(P_{(yellow_{R1})ayu}, N_{ayu}^{DSR}).$

Kodiak has limited port sampling beyond the main harbors but has a robust hydroacoustic survey that is used to quantify black rockfish abundance across the management area and uses  stereocameras to derive species compositions of the hydroacoustic data (Tscherisch et al. 2023). This data was used as supplementary data to further inform the model on the proportion of pelagic rockfish that are black in Kodiak areas. Where angler landing data is available, they demonstrate a higher proportion of black rockfish relative to the hydroacoustic survey and thus the proportion of black rockfish in the hydroacoustic sample related to the true proportion such that 

$P_{(black|pelagic)ayu}^{HA} ~\sim~ P_{(black|pelagic)ayu} + ae_{au}$

where $ae_{au}$ is the angler effect for each area and user group modeled hierarchically around a mean of 0. Predicted $P_{(black|pelagic)ayu}^{HA}$ assumed a beta distribution such that

$P_{(black|pelagic)ayu}^{HA} ~\sim~ beta(\alpha_{HA},\beta_{HA})$

where

$\alpha_{HA} ~=~ (P_{(black|pelagic)ayu}^{HA})^2 * \frac{1 - P_{(black|pelagic)ayu}^{HA}}{\frac{var_{P_{HA}}-1}{P_{(black|pelagic)ayu}^{HA}}},$

$\beta_{HA} ~=~ (\alpha_{HA}) * \frac{1}{P_{(black|pelagic)ayu}^{HA} - 1},$

$var_{P_{HA}} ~=~ (P_{(black|pelagic)ayu}^{HA} * cvP_{(black|pelagic)ayu}^{HA})^2$

where $cvP_{(black|pelagic)ayu}^{HA}$ is the coefficient of variation for the hydroacoustic proportions 

$cvP_{(black|pelagic)ayu}^{HA} ~=~ \frac{\sqrt{varP_{(black|pelagic)ayu}^{HA}}}{P_{(black|pelagic)ayu}^{HA}}$

and the variance is approximated using the delta method (Casella and Berger 2002) as 

$varP_{(black|pelagic)ayu}^{HA} ~=~ (\frac{1}{n_{pel}})^2 * varN_{black} + (\frac{n_{black}}{n_{pel}^2})^2 * varN_{pel}$

where $varN_{black}$ and $varN_{black}$ are the variance of the estimated number of black and pelagic rockfish in the hydroacoustic survey, respectively (Tscherisch et al. 2023). The covariance term was omitted as it was at or near 0.

The average weight of rockfish by species, user, area and year was modeled hierarchically at several levels within regions such that

$wt_{(comp)ayu} ~\sim~ Lognormal(wt_{(comp)au},\sigma_{wt_{(comp)au}}) ~\sim~ Logormal(wt_{(comp)a},\sigma_{wt_{(comp)a}}) ~\sim~ Logormal(wt_{(comp)region},\sigma_{wt_{(comp)}})$

where *region* refers to Kodiak, Southcentral and Southeast. Mean weights and variance were calculated as **XXX**.

## Priors

Priors used in this model ranged from uninformative to very informative. We chose loose priors whereever possible, but the logistic curves used to hindcast the $pH_{(comp)ayu}$ and $P_{(comp)ayu}$ required fairly informative priors to achieve convergence in the model (Table PRIORs, PRIORs, PRIORs). Prior development began with the most uninformative options and were tightened during model development to achieve convergence and reasonable logistic curves based on the data. 

Many of the parameters and priors are modeled hierarchically across regions and/or years. The penalized spline used to fit the overall harvest models the lambda terms hierarchically by region while the model assumes a single standard deviation for the random effects of the species composition logistic curve. The standard deviation of the random effect of the proportion harvested was modeled hierarchically by species. The beta terms in the $P_{(comp)ayu}$ and $P_{(comp)ayu}$ curves were also modeled hierarchically by region such that all CFMU's within the same region share the same hyperprior for those terms. 

It is also work noting a particularly restrictive prior used on the $\beta4_{(pH)ayuc}$ terms that describe the offset of the pH logistic curve for unguided anglers (Table pH_PRIOR). The only information on unguided releases is the biases and imprecise estimate for all rockfish from the SWHS. To generate an estimate for unguided anglers required an assumption that harvest patterns of unguided anglers generally followed those of guided anglers fairly closely and as such the prior for the $\beta4_{(pH)ayuc}$ terms is very informative to maintain reasonable estimates of unguided releases with manageable credibility intervals.

## Model platform and diagnostics

The model was run using JAGS version 4.3.1 using the jagsUI and rjags packages (Plummer et al. 2006, Lunn et al. 2009, Plummer 2024) on the statistical R Statistical Software (v4.4.3;R Core Team 2021). Model convergence was judged by examining traceplots and ensuring that Rhat values were below 1.1 (Gelman and Rubin 1992).

# Results

The estimation model was able to estimate harvests, releases and total removals (harvests plus release mortalities) with near complete convergence of model parameters. Harvest estimates were very similar to Howard et al. (2020) estimates, but differed more in areas where private anglers were the dominant user group. Release estimates were also very similar to guided estimates from the Howard estimates which is not surprising given that both methods rely on the census derived from the logbook program. Estimate of unguided releases for black rockfish were generally substantially lower than the Howard methods, although the Bayesian credibility intervals frequently overlapped with the Howard estimates. The large change is to be expected given the bias correction undertaken in the Bayesian model and the more appropriate use of the proportion harvested data from the logbook program. Yelloweye release estimates also differed from the Howard estimates for private anglers although the direction of the difference varied by CFMU. 

Explanation of unconverged parameters: 

1) Spikyness and parameters near 0 / bounds.
2) BSAI and SOKO2SAPs
3) beta terms when difficult to fit logistic curves. 

## Residual Patterns

Residual patterns of the fit of the data to the SWHS data were generally satisfactory, with a few exceptions. Large harvest residuals (Figure SWHS_H_RESIDS) were often associated with poor precision in the SWHS estimates in all regions. PWSO demonstrated odd residual patterns associated with large uncertainty prior to 2000 with the model predicting higher harvests than demonstrated in the SWHS. Kodiak areas demonstrated some strange residual patterns in the WKMA and eastside CFMU's, but were generally associated with poor precision in the estimates. Southeast harvests showed generally satisfactory residual patterns, although SSEO model results were consistently higher than survey estimates prior to 1992. 

Residual patterns for the SWHS release data showed much larger residuals as would be expected from the much less precise release estimates (Figure SWHS_R_RESIDS). Overall, the release residuals tended to be more positive than negative. PWSO releases demonstrated the same pattern as that of the harvests. 

Residual patterns of the fit to the logbook data show some patterns but are minor with respect to the overall number of fish being estimated (Figure LB_RESIDS). Logbook data is fit with a poisson distribution which assumes a very small error and thus the model estimates are usually within 1% of the logbook value for both harvests and releases. There were some odd patterns in the North Gulf and both Prince William Sound CFMUs where the model predicted less harvests than logbook entries in the early years of the program and across all of southcentral and Kodiak CFMU's the residuals are larger during that time period.  

## Bias Estimation

Model predicted bias in SWHS harvest and release data tracked the observed bias well across years and CFMUs (Figure YEARAREA_BIAS) and demonstrated that SWHS estimates were generally biased low while release estimates were biased high (Figure MEAN_BIAS). Observed and estimated harvest bias were very consistent with the exception of the very data poor BSAI CFMU (Figure YEARAREA_BIAS). Estimated release bias tracked observed release bias but generally smoothed the more variable release bias observed in the data. This is likely the result of far less precision in the SWHS release estimates which would result in the model more closely adhering to the harvest data in fitting the overall model. Nevertheless, the observed release bias are generally within the 95% credibility intervals of the model estimated bias .   

## Proportion Harvested

Estimates of the proportion harvested (*pH*) for guided pelagic rockfish accurately tracked the logbook data and the logistic curve fit to that data demonstrated reasonable patterns and uncertainty for hindcasting (Figure pH_PEL). All CFMUs demonstrated a similar pattern where retention of pelagic rockfish has increased since the logbook program began in 1998, with very few black rockfish being released in recent years. 

The proportion harvested for unguided anglers was assumed to track the same patterns as guided anglers, which the model captures satisfactorily. The confidence intervals around unguided *pH* were appropriately large given the lack of data specific to unguided releases other than the SWHS estimates for all rockfish releases. Instances where *pH* of guided and unguided anglers diverge were the result of the model's balancing of all the data such that the sum of species and complex specific rockfish releases in each area equal the bias corrected SWHS estimates of total releases.

The proportion harvested of yelloweye rockfish demonstrated a very different pattern from pelagics whereby guided anglers have retained almost all landed fish until recent years when management restrictions came into effect (Figure pH_YE). This is most obvious in the Southeast CFMU's where yelloweye retention was prohibited beginning in 2020 and to a lesser degree in Prince William Sound (CFMU PWSI and PWSO) where restrictions also came into effect. The model tracked this data well and the hindcasting logistic curve tracks the high retention probablitiy back in time.

The proportion harvested of unguided yelloweye rockfish was generally estimated to be lower than for guided anglers across CFMUs, but captures the same dynamic as guided anglers and reflects management restrictions that have come into play in recent years. As expected, credibility intervals for unguided anglers were significantly larger and encompased guided angler estimates. 

For non-pelagic / non-yelloweye rockfish ($pH_{other}$) the proportion harvested demonstrated variable patterns across regions (Figure pH_OTHER). Central regions demonstrated a static pattern with the exception of Cook Inlet where retention probabilities increased over the course of observed time periods. Kodiak demonstrated increasing retention probabilities with the exception of the WKMA CFMUs which were static. In contrast, Southeast CFMU's show a pattern similar to that of yelloweye rockfish with very high retention until management restrictions came into effect in recent years. As with the pelagic and yelloweye categories, unguided *pH* tracked the guided estimates as model design intended. 

## Species Composition

The species composition of the harvests tracked the observed data well and produced reasonable logistic curves for hindcasting. The pelagic proportion demonstrated either an increasing trend in the harvests (Southeast and Prince William Sound) or a static trend (Kodiak, Cook Inlet and North Gulf)(Figure P_PEL). Model estimates tracked the observed data well and fell towards the trend line when sample sizes were small or absent. The logistic hindcasting curve appeared to match the trends in the data and encompassed the uncertainty derived from the random effect estimates. The $\beta4_{(P_{comp})ayuc}$ term had a much less informative prior than applied to $\beta4_{(pH)ayuc}$ terms but nevertheless resulted in fairly minor differences between guided and unguided anglers with the exception of PWSI and, to a lesser extent, SSEI. 

The proportion of pelagic rockfish that were black proved to be static, with the exception Cook Inlet, which showed an increase, and NSEI, which showed a decrease (Figure P_BLACK). The model tracked observed values well and applied the uncertainty derived from the random effects in the hindcast values. Applying the hydroacoustic survey data to Kodiak $P_{(black)ayu}$ proved to be both informative and useful in estimating those values. Without that data the estimates tended toward the hyperprior values as informed by the Northeast data and resulted in credibility intervals that stretched from 0 to 1. The hydroacoustic data clearly demonstrates higher black rockfish proportions in these other areas and the model was able to generate far more precise and realistic estimates of these parameters. 

The yelloweye proportion demonstrated a static portion of the harvest in Kodiak and subtle decline in Southcentral areas and a precipitous drop in Southeast where management restrictions were in place in recent years (Figure P_YE). Southcentral data is noisy but the fitted logistic curve appeared to capture the change in species composition during the observed time period and provided acceptable values for hindcasting with the appropriate level of uncertainty. Kodiak yelloweye trends were poorly informed due to a lack of data associated with historically low harvests of yelloweye in this region. Southeast yelloweye proportions (relative to the DSR assemblage) were also somewhat noisy, but the trends in the data were adequately captured by the fitted logistic curve. 

The proportion of the Southeast harvest that were DSR and slope rockfish also appeared to track the data well and provide reasonable predictions for hindcasting (Figure P_DSR, P_SLOPE, P_SLOPE_REL). The trends in these two assemblages indicate that prior to restrictions being placed on yelloweye and DSR, the vast bulk of the non-pelagic harvests in Southeast were DSR species with slope species comprising only a minor proportion. However, with the closure of yelloweye and restrictions on DSR the proportion of the harvest that were slope rose precipitously in recent years. 

## Proportion Guided

Data on the proportion of total rockfish catches that were guided is lacking and there was no trend estimated for hindcasting these parameters. The model captured the observed estimates within the credibility intervals, but tended to smooth the observed estimates (Figure pG). Without a modeled trend, the model essentially uses a long-term average as described by the estimated beta distribution of the pG parameters to hindcast the guided proportion in the model. Credibility in the hindcasted values reflect the variability occuring during the observed time period.

## Weight 

The model estimated weights matched the observations as would be expected and tended to the hyperprior means when data was absent or sample sizes were small (Appendix B). 

## Harvest, Release and Total Removal Estimates

### Harvests 

Total rockfish harvests demonstrate a generally increasing trend across the time series with some plateauing in recent years as a result of management restrictions (Figure H_ALL; Appendix C1). Prior to 1998 when the logbook program went into effect, there is greater uncertainty in estimates and harvests were generally low. Some areas such as Cook Inlet (CI), North Gulf (NG), Northeast Kodiak and many of the Southeast CFMUs demonstrate consistent harvests during that time period. Harvest estimates from the Bayesian model are very consistent with Howard method estimates with some exceptions. There are some difference in the 1998-2001 time period when the Howard methods made assumptions to deal with data limitations that were more appropriately handled with the hierarchical model in the Bayesian model. There are also differences in some of the Kodiak areas where the Howard methods borrowed values from the most data rich Kodiak CFMUs whereas the Bayes model applies a hierarchical approach to leveragin all of the data.  

Black rockfish harvests demonstrate an increasing trend over the time series that is dominated by guided anglers with the exception of PWSI and Northeast Kodiak (Figure H_BLACK, Appendix C2). Harvests prior to 1998 are generally low, but the North Gulf (NG), Northeast Kodiak, and the SSEI, NSEI and CSEO CFMU's in Southeast had significant harvests during that time period. Guided estimates are very precise since the logbook program went into effect and port sampling programs provide robust samples for understanding the black rockfish proportion of the pelagic harvest. Unguided harvests are more uncertain as would be expected given their reliance on the SWHS estimates. Unguided estimates are similar to the Howard estimates and where they differ the credibility intervals of the Bayesian estimates include Howard estimates in most cases. They differ significantly in the PWSI where unguided harvests are the same magnitude as guided harvests and thus bias corrections made in the Bayesian model would be expected to have a larger effect on those estimates.  

Yelloweye rockfish harvest also demonstrate increasing harvests but with reductions in recent years that reflect management actions taken by the department (Figure H_YE, Appendix C3). The Bayesian model demonstrates consistent and steady harvests in many CFMU's prior to 1998 and with the SSEI and CSEO demonstrating appreciable harvests. As with black rockfish, yelloweye rockfish guided harvests estimates agree with Howard estimates. Unguided yelloweye harvests were also similar to Howard estimates with the exception of the PWSI CFMU. This is the only area where private harvests significantly out number guided harvests and thus the effect of bias correction in the model has a more pronounced effect. 
 
Non-yelloweye DSR harvests show very similar patterns to yelloweye and strong agreement with Howard estimates (Figure H_DSR and Appendix C4) and slope rockfish harvests show in increasing trend that is less pronounced than the other species and complexes (Figure H_SLOPE and Appendix C5). Although slope *pH* increased dramatically in recent years, overall harvests did not as non-pelagic harvests overall fell during recent years in Southeast. The slope estimates show some differences from Howard estimates in EWKT CFMU because the Howard methods borrowed values from other areas whereas the Bayesian model uses hierarchical modelling to deal with low or absent samples. 

### Releases

The release estimates for all rockfish are substantially less than harvests and demonstrate variable trends over the course of the time series with substantial uncertainty in the estimates (Figure R_ALL and Appendix C1). Estimates from the pre-1998 period were sometimes similar to the low end of the post-1998 period or demonstrate an increase as the fishery in that CFMU developed. The trends in the Bayesian model follow the trends in the Howard estimates, but are generally lower and exhibit less variability. In particular, the Bayes estimates are significantly lower in the early 2000s when the Howard methods relied on assumptions and long term averages to compensate for the lack of logbook data on yelloweye releases (Figure DATA).  

Releases of black rockfish demonstrate a relatively steady trend with an increase in the early 2000s as anglers began to target the species and then a decline as angler retention in increased (Figure R_BLACK, Figure BRF_pH, Appendix C2). Estimates of guided releases are very precise since 1998 owing to logbook records of pelagic releases and the port sampling program's estimate of black rockfish proportions in the pelagic species complex. Prior to 1998, guided release estimates demonstrate significant uncertainty. Estimates of unguided releases have substantial uncertainty as a result of data specific to unguided release numbers and the reliance on the *pH* demonstrated by guided anglers. Unguided black rockfish release estimates were substantially lower than the Howard estimates, although the upper credibility of the Bayes estimates often included the Howard estimates. 

Yelloweye release estimates demonstrate fairly steady trends with pronounced uncertainty around the unguided estimates (Figure R_YE and Appendix C3). The lack of unguided angler specific release estimates coupled with large variances in the SWHS total rockfish release estimates and relatively small release numbers result in the large variances. However, retention of yelloweye rockfish has been historically high (Figure YE_pH) and the overall release estimates are generally low. Unguided release estimates also differ substantially from the Howard estimates but, unlike black rockfish, are sometime higher. In almost all cases the credibility intervals from the Bayes model include the Howard estimates. 

Non-yelloweye DSR demonstrate similar release patterns to yelloweye rockfish and lower unguided estimates than Howard (Figure R_DSR and Appendix C4) while slope rockfish show very low release numbers for most of the time seris and a large, uptick in recent years with substantial uncertainty (R_SLOPE and Appendix C5). 
 
### Total Removals in Biomass

After factoring in release mortalities and converting to biomass total removals of rockfish in sport fisheries were calculated. Pelagic and black rockfish release mortality is relatively low even before the introduction of DWRs and with high retention in recent years when harvest have increased, release mortalities represent a trivial component of overall fishery removals (Figure BRF_M, PEL_M, Appendix B1 and B6). DSR (including yelloweye) and slope rockfish assemblages experienced high release mortality prior to DWR requirements and even with DWR experience appreciable mortality rates (Figure REL_M). As such, release mortalities comprised a modest but appreciable contribution to overall mortalities (Figure YE_M, DRS_M and SLOPE_M, Appendix C3, C4 and C5). 

## Retrospective Patterns

Oi. Generally good. Yikes... 

# Discussion

This Bayesian approach to reconstructing historical rockfish removals and calculating current rockfish removals build and improve on the foundation established by Howard et al. (2020). This new approach offers a unified methods that encompasses all of the necessary steps to go from the SWHS, logbook and port sampling data to produce estimates of harvests, releases and total biomass removal estimates necessary to conduct stock assessments. These methods are reproducible and offer the first documentation of the biomass and mortality calculations that have been used since the Howard methods were first adopted and will lead to greater consistency and transparency in accounting for rockfish removals in Alaska waters. These methods improve on the Howard methodology by accurately addressing bias in the SWHS data, models the release data in a more realistic process, uses hierarchical modelling to deal with low or absent samples, and generates a time series back to 1977 by utilizing all of the available data. 

Harvest estimates produced with these methods are very consistent with the Howard estimates and differ only where the Bayesian methods offer improvements on a key, but flawed, assumption about the use of SWHS data. The Howard methods rely on the SWHS ratio of guided:unguided harvests to expand guided logbook harvests to generate unguided estimates which makes the assumption that the guided:unguided ratio applies equally to all species and species complexes even though the ratio is derived from total rockfish estimates in the SWHS. Most CFMUs have considerably higher harvests by guided users and thus this flaw is less significant as the Bayesian estimates of unguided harvests align well with Howard estimates. However, where guided anglers are in the minority (i.e., PWSI) we see larger differences in the unguided harvests that demonstrate the limitations of that approach.   

The Bayesian approach to estimating releases produces very different estimates from the Howard approach, and in particular unguided releases. The Howard approach uses the same methods for estimating unguided releases as it does for harvests as it applies the SWHS ratio of guided:unguided release of all rockfish to the logbook release data. However, the Howard methods do not address bias in those estimates and assumes the ratio is equal for all species. In contrast to SWHS harvest estimates, release estimates are biased high (i.e., anglers over report their releases relative to logbook data) with a much larger magnitude in the bias relative to harvests. Rather than multiplying the logbook release estimates by the unguided:guided ratio of releases in the SWHS data, the Bayesian model corrects the SWHS release estimates and ensures that releases of the three logbook categories sum to that value, ensuring a more process and data driven estimation procedure. In many cases the Howard method results in unguided release estimates that are at or above guided release estimates even when the harvest of unguided anglers is substantially less (Figures H_BLACK and R_BLACK). This would imply that unguided anglers are discarding fish at a far higher rate than are guided anglers . 

The flaw in the Howard methods is apparent when examining release estimates of rockfish in southeast CFMU’s since 2020 when yelloweye retention was prohibited and DSR retention restricted. During these years the logbook data demonstrates almost 100% retention of black rockfish while regulations reduce yelloweye retention to zero and limited DSR retention to 1 per day. In most of Southeast guided harvests are significantly higher than unguided harvests but the SWHS unguided:guided release ratio suggests more releases by unguided anglers. The result of the Howard methods is that the guided releases are expanded to derive unguided estimates, resulting in estimates of unguided black rockfish releases far above the guided estimates while the harvest estimates display the opposite pattern. The CSEO is particularly indicative of this seeming contradiction where guided harvests of black rockfish are over 4 times that of the unguided anglers while the Howard methods generate unguided release estimates 2 to 3 times that of guided anglers. Because the SWHS data is for all rockfish combined it does not address the different retention probabilities by species complexes which are particularly divergent in southeast since 2000 due to management action.

The Bayesian approach is not without flaws and required making the key assumption that retention probabilities have followed similar trends in both user groups. Projecting release estimates back in time required relating releases to the harvest data and necessitated estimating retention probability (*pH*).  However, initial efforts to maintain consistency with the Howard methods and model *pH* for all rockfish proved to be untenable given the underlying inconsistency in retention probability of pelagics and yelloweye in the logbook data. As such, the approach was altered to estimating pH by species and species complex. This worked well for guided anglers because of the logbook data but was challenging to deal with for unguided anglers.

Estimating unguided releases thus required an assumption that retention probabilities for unguided anglers followed similar trends to that of unguided anglers. On the face of it this seemed reasonable but there are some estimates that give pause. The assumption seemed reasonable for yelloweye given that yelloweye are prized by anglers and one would expect unguided anglers to also retain most of their catch. Similarly, the popularity of black rockfish increased as halibut and salmon restrictions increased resulting in the charter fleet targeting them as part of their business model and it was expected that unguided angler tendencies would be similar as the public developed an appreciation for the fish. Estimating unguided releases was thus a combination of the adhering to the retention probabilities evident in the logbook data and adjusting those rates such that the estimated unguided releases by species sum to the total rockfish release estimate from the bias corrected SWHS estimate of total rockfish releases. This results in pH estimates with much larger credibility intervals for unguided anglers when compared to guided anglers which was deemed appropriate given the lack of information. However, some of the flaws in this assumption were apparent in some CFMUs where yelloweye harvests and releases occur in low numbers such as Cook Inlet (CI) and Northeast Kodiak. In these areas the models attempt to balance release estimates of the different species results in pH estimates for yelloweye that seem suspiciously low given the value anglers typically place on this species (Figure YE_pH). Overall yelloweye harvests and releases are low in those areas and thus the estimates are not likely to have serious implications, but they do highlight a potential weekness in the new approach. Similarly, the Bayes model estimates near complete retention of black rockfish by unguided anglers in recent years and minimal release estimates. While these estimates may seem suspect, there are large credibility intervals associated with the estimates and, moreover, release mortality rates are very low for black rockfish and thus the effects on total removals from the population would be minimal.

Release estimates were also restricted to the three categories collected in logbook data; pelagic, yelloweye and “other” (non-pelagic, no-yelloweye) and thus the species apportionment calculations were based on sampling of the harvest. Deriving black rockfish from the pelagic species complex using harvest samples were reasonable given that management treats all pelagics the same and there is no information suggesting anglers preferentially retain one pelagic species over another. In southeast Alaska, it was also necessary to apply the species composition of the harvest to estimate the number of non-yelloweye DSR and slope rockfish released from the release estimates of “other” rockfish. This also seemed a reasonable assumption given that these species would be encountered during similar fishing practices (jigging on the bottom) and that anglers would value these species to a similar extent.

It must also be pointed out that release estimates are based on the assumption that charter captains accurately report the number of fish they release. While law enforcement provides incentives for the accurate recording of harvests, enforecement of release reporting is not possible. Estimated bias of SWHS release estimates is extremely high, suggesting that angler over estimate the number of fish released by a factor of 2 or more while underestimating the number of fish harvested. Recall bias, which may be worse with released fish relative to harvests, may partially explain these results but it cannot be ruled out that release estimates from the logbook data are not entirely accurate. Models were explored to loosen the assumption that logbook releases act as a census, but to date no viable model was developed that produced reasonable release estimates. The SWHS is currently undergoing a modernization project that may shed more light on how to resolve some of these issues.

One key parameter in the model that is poorly informed in the proportion guided, *pG*. There is limited data on this parameter and was thus modeled as long term average using a beta distribution when data was absent (Figure pG). Ideally, this would be estimated as a trend similar to how retention probability and species proportions were handled in the model, however the available data did not suggest obvious trends that would support that approach. If *pG* has changed significantly it would affect the estimates in the model and thus remains a question mark in the approach. If data were to become available the model could be updated to accommodate it to produce more accurate estimates, but in the absence of that data it is hoped that credibility intervals capture the true values.  

## Conclusions and Recomendations

Managers prefer harvests to remain static once estimated but harvests, releases and removals are all estimated quantities that can change with improved science that reflects our understanding of the system. As the data is updated annually estimates are likely to shift to some degree. The retrospective exam showed that estimates from the pre-1998 period can change substantially as the shape of the species composition and retention probability curves change with the addition of data. The priors used to develop those curves are based on the data through 2023 and pre-1998 values should remain fixed to the estimates provided in this report. 

With regard to contemporary estimates, the retrospective exam showed that harvest estimates are very stable and as harvest mortalities constitute the bulk of total removals those estimates will also remain mostly stable. Similarly, guided release estimates are  extremely stable given the logbook data acting as a census. The one quantity that is least stable are the unguided release estimates which are ultimately reliant on the *pH* parameter. Although unguided removal estimates are likely to change to **retro results degree** the overall removal estimates should be fairly stable given that total release mortality is a minor component of overall removals. Given these results, **it is recommended that estimates be updated for a period of 5 years after which they should remain fixed** barring new science that requires recalculating removals. 

In conclusion, these new estimates of rockfish harvest, release and removals offer an improved and more repeatable approach to catch accounting for this highly targeted and vulnerable group of fish. These methods build on the location accounting system built by Howard et al. (2020) as well as the validation of the port sampling representativeness. In addition to extending the time series, the new methods are more reflective of the angling process, better capture the uncertainty in the data, more appropriately share information within regions, and provide a unified and centralized approach to calculating, reporting and archiving rockfish harvests, releases and removals in Alaska waters. 

# Acknowledgments

Sport harvest reconstructions provided in this document were made possible by the devoted time and effort of many people administering the data collection projects used in these analyses. First and foremost, it needs to be acknowledged that although this report may seem critical of the Howard methods, this effort does not exist without the foundational work undertaken by Katie Howard and her coauthors in developing these methods, establishing and validating the relevancy of the data, and developing a system of accurately assigning data to appropriate CFMUs that are now available annually from the SWHS and logbook programs. Similarly, those overseeing and running those programs deserve special thanks for the high quality work and products produced including Nick Smith and Jacob Bozzini from the SWHS program and Ben Jevons and Kyla Buster from the Saltwater Guide Logbook program. This project also highlight the high value of the port sampling programs with particular thanks going to **LIST from Chris and Clay**. We would also like to thank Tyler Polum and Philip Tschersich for the Kodiak hydroacoustic data and advice. We would like to thank Adam Reimer for developing the initial approach to this model and Hamachan Hamazaki for his review of this work. 

# Literature Cited

Casella, G., & Berger, R. L. (2002). Statistical Inference (2nd ed.). Duxbury.

Eilers, Paul H. C., and Brian D. Marx. 1996. “Flexible Smoothing with B-Splines and Penalties.” Statistical Science 11: 89–121.

Gelman, A.. Prior distributions for variance parameters in hierarchical models. Bayesian
Analysis, 1:515–533, 2006.

Gelman, A. and D. Rubin. Inference from iterative simulation using multiple sequences.
Statistical Science, 7:457–511, 1992.

Howard, K. G., S. Campen, F. R. Bowers, R. E. Chadwick, J. W. Erickson, J. J. Hasbrouck, T. R. McKinley, J. Nichols, N. Nichols, A. Olson, J. Rumble, T. T. Taube, and B. Williams. 2019a. ADF&G Statewide Rockfish Initiative: Strategic plan 2017–2020. Alaska Department of Fish and Game, Division of Commercial Fisheries, Regional Information Report 5J19-05, Anchorage.

Howard, K. G., D. Evans, and A. St. Saviour. 2020. Reconstructed sport harvests and releases of black and yelloweye rockfishes in the Gulf of Alaska, 1998–2018. Alaska Department of Fish and Game, Fishery Data Series No. 20-25, Anchorage.

Lang, Stefan, and Andreas Brezger. 2004. “Bayesian P-Splines.” Journal of Computational and Graphical Statistics 13 (1): 183–212.

Lunn D, Spiegelhalter D, Thomas A, Best N. (2009) The BUGS project: Evolution, critique and future directions. Statistics in Medicine, 28:3049-67.

Plummer M (2024). _rjags: Bayesian Graphical Models using MCMC_. R package version 4-16,
  <https://CRAN.R-project.org/package=rjags>.

Plummer M, Best N, Cowles K, Vines K (2006). CODA: Convergence Diagnosis and Output Analysis for MCMC, R News, 6:7-11.

R Core Team (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.

Ruppert, David, Matt P. Wand, and Raymond J. Carroll. 2003. Semiparametric Regression. Cambridge University Press.

Tschersich, P., J. Dissen, and W. Gaeuman. 2023. Westward Region hydroacoustic survey for black rockfish Sebastes melanops abundance, 2007–2022. Alaska Department of Fish and Game, Fishery Data Series No. 23-31, Anchorage.





















